## Diffusion Limited Aggregation

In [115]:
import numpy as np
import random

In [118]:
dims = (10,10)
starter_mat = np.zeros(dims)

In [119]:
def spawn_walkers(mat, N=10):
    """
    spawn N random walkers on the given matrix
    
    args:
        :mat - matrix to place walkers
        :N (int) - number of walkers to spawn
    """
    # viable locations to spawn are those that are unoccupied
    viable_loc_mat = np.ones(mat.shape) - mat
    assert sum(sum(viable_loc_mat)) >= N, "There are not {} spawn locations".format(N)
    
    viable_locs = list(np.array(np.where(viable_loc_mat > 0)).T)
    
    spawn_locs = random.sample(viable_locs, N)
    args = zip(*spawn_locs)
    mat[list(args)] = 1
    print(mat)

In [120]:
spawn_walkers(starter_mat, N=10)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [78]:
A = np.ones((10,10))

In [79]:
A[[1,1],[2,2]] = 3

In [80]:
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])